apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../api/artifacts/apiserver/rbac.yaml
- ../api/artifacts/apiserver/apiservice.yaml
- ../api/artifacts/apiserver/app.yaml
- ./rbac-flowcontrol.yaml
      
patches:
- target:
    kind: Deployment
    name: apiserver
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ko://github.com/phosae/x-kubernetes/api-aggregation-runtime/cmd/hello-apiserver
- target:
    kind: Service
    name: apiserver
  patch: |-
    - op: replace
      path: /spec/ports/0/targetPort
      value: 443
- target:
    kind: Deployment
    name: apiserver
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--etcd-servers=http://localhost:2379", "--feature-gates", "ContextualLogging=true", "--authentication-token-webhook-cache-ttl=1s", "--authorization-webhook-cache-authorized-ttl=100ms", "--authorization-webhook-cache-unauthorized-ttl=100ms", "-v", "9"]