/*
boilerplate text in generated file header
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/phosae/x-kubernetes/api/transformation/v1beta1/generated.proto

package v1beta1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Base64) Reset()      { *m = Base64{} }
func (*Base64) ProtoMessage() {}
func (*Base64) Descriptor() ([]byte, []int) {
	return fileDescriptor_74422ff5091607f4, []int{0}
}
func (m *Base64) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Base64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Base64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base64.Merge(m, src)
}
func (m *Base64) XXX_Size() int {
	return m.Size()
}
func (m *Base64) XXX_DiscardUnknown() {
	xxx_messageInfo_Base64.DiscardUnknown(m)
}

var xxx_messageInfo_Base64 proto.InternalMessageInfo

func (m *Base64Spec) Reset()      { *m = Base64Spec{} }
func (*Base64Spec) ProtoMessage() {}
func (*Base64Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_74422ff5091607f4, []int{1}
}
func (m *Base64Spec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Base64Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Base64Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base64Spec.Merge(m, src)
}
func (m *Base64Spec) XXX_Size() int {
	return m.Size()
}
func (m *Base64Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Base64Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Base64Spec proto.InternalMessageInfo

func (m *Base64Status) Reset()      { *m = Base64Status{} }
func (*Base64Status) ProtoMessage() {}
func (*Base64Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_74422ff5091607f4, []int{2}
}
func (m *Base64Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Base64Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Base64Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base64Status.Merge(m, src)
}
func (m *Base64Status) XXX_Size() int {
	return m.Size()
}
func (m *Base64Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Base64Status.DiscardUnknown(m)
}

var xxx_messageInfo_Base64Status proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Base64)(nil), "github.com.phosae.x_kubernetes.api.transformation.v1beta1.Base64")
	proto.RegisterType((*Base64Spec)(nil), "github.com.phosae.x_kubernetes.api.transformation.v1beta1.Base64Spec")
	proto.RegisterType((*Base64Status)(nil), "github.com.phosae.x_kubernetes.api.transformation.v1beta1.Base64Status")
}

func init() {
	proto.RegisterFile("github.com/phosae/x-kubernetes/api/transformation/v1beta1/generated.proto", fileDescriptor_74422ff5091607f4)
}

var fileDescriptor_74422ff5091607f4 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xed, 0x52, 0x45, 0xe4, 0xa8, 0x90, 0xf0, 0x14, 0x65, 0xb8, 0xa2, 0x0c, 0x88, 0xa5,
	0x77, 0x04, 0x55, 0x11, 0x1d, 0x58, 0x2c, 0x01, 0x62, 0x40, 0x45, 0x66, 0x63, 0x29, 0xcf, 0xce,
	0x8b, 0x7d, 0x18, 0xfb, 0x4e, 0xbe, 0xe7, 0xa8, 0x6c, 0x7c, 0x04, 0x3e, 0x14, 0x43, 0xc6, 0x8e,
	0x9d, 0x2a, 0x62, 0xbe, 0x08, 0xf2, 0xd9, 0xd4, 0x81, 0x0a, 0x21, 0x95, 0xcd, 0xef, 0xdd, 0xfd,
	0x7f, 0xbf, 0xbf, 0x6c, 0x99, 0xbd, 0x4e, 0x15, 0x65, 0x75, 0x2c, 0x12, 0x5d, 0x48, 0x93, 0x69,
	0x0b, 0x28, 0xcf, 0x8f, 0xf2, 0x3a, 0xc6, 0xaa, 0x44, 0x42, 0x2b, 0xc1, 0x28, 0x49, 0x15, 0x94,
	0x76, 0xa5, 0xab, 0x02, 0x48, 0xe9, 0x52, 0xae, 0xe7, 0x31, 0x12, 0xcc, 0x65, 0x8a, 0x25, 0x56,
	0x40, 0xb8, 0x14, 0xa6, 0xd2, 0xa4, 0x83, 0x93, 0x01, 0x25, 0x3a, 0x94, 0x38, 0x3f, 0x1b, 0x50,
	0x02, 0x8c, 0x12, 0xbf, 0xa3, 0x44, 0x8f, 0x9a, 0x1e, 0xed, 0xb4, 0x48, 0x75, 0xaa, 0xa5, 0x23,
	0xc6, 0xf5, 0xca, 0x4d, 0x6e, 0x70, 0x4f, 0x9d, 0x69, 0x7a, 0x9c, 0x3f, 0xb3, 0x42, 0xe9, 0xb6,
	0x5c, 0x01, 0x49, 0xa6, 0x4a, 0xac, 0x3e, 0x4b, 0x93, 0xa7, 0xed, 0xc2, 0xca, 0x02, 0x09, 0xe4,
	0xfa, 0x46, 0xbf, 0xa9, 0xfc, 0x5b, 0xaa, 0xaa, 0x4b, 0x52, 0x05, 0xde, 0x08, 0x2c, 0xfe, 0x15,
	0xb0, 0x49, 0x86, 0x05, 0xfc, 0x99, 0x9b, 0x7d, 0xdb, 0x63, 0xa3, 0x10, 0x2c, 0x2e, 0x8e, 0x83,
	0x0f, 0xec, 0x6e, 0x5b, 0x67, 0x09, 0x04, 0x13, 0xff, 0xa1, 0xff, 0xf8, 0xde, 0xd3, 0x27, 0xa2,
	0xa3, 0x8a, 0x5d, 0xaa, 0x30, 0x79, 0xda, 0x2e, 0xac, 0x68, 0x6f, 0x8b, 0xf5, 0x5c, 0x9c, 0xc6,
	0x1f, 0x31, 0xa1, 0x37, 0x48, 0x10, 0x06, 0x9b, 0xab, 0x43, 0xaf, 0xb9, 0x3a, 0x64, 0xc3, 0x2e,
	0xba, 0xa6, 0x06, 0x29, 0xdb, 0xb7, 0x06, 0x93, 0xc9, 0x9e, 0xa3, 0xbf, 0x10, 0xb7, 0xfe, 0x08,
	0xa2, 0xab, 0xfc, 0xce, 0x60, 0x12, 0x1e, 0xf4, 0xca, 0xfd, 0x76, 0x8a, 0x9c, 0x20, 0xd0, 0x6c,
	0x64, 0x09, 0xa8, 0xb6, 0x93, 0x3b, 0x4e, 0xf5, 0xea, 0xff, 0x55, 0x0e, 0x17, 0xde, 0xef, 0x65,
	0xa3, 0x6e, 0x8e, 0x7a, 0xcd, 0xec, 0x39, 0x63, 0x43, 0xa5, 0x40, 0xb2, 0xf1, 0x4a, 0xe1, 0xa7,
	0xe5, 0x5b, 0xa0, 0xcc, 0xbd, 0xca, 0x71, 0xf8, 0xa0, 0x0f, 0x8e, 0x5f, 0xfe, 0x3a, 0x88, 0x86,
	0x3b, 0xb3, 0x05, 0x3b, 0xd8, 0xd5, 0x04, 0x8f, 0xd8, 0x48, 0xd7, 0x64, 0x6a, 0xea, 0xd3, 0xd7,
	0xda, 0x53, 0xb7, 0x8d, 0xfa, 0xd3, 0xf0, 0x6c, 0xb3, 0xe5, 0xde, 0xc5, 0x96, 0x7b, 0x97, 0x5b,
	0xee, 0x7d, 0x69, 0xb8, 0xbf, 0x69, 0xb8, 0x7f, 0xd1, 0x70, 0xff, 0xb2, 0xe1, 0xfe, 0xf7, 0x86,
	0xfb, 0x5f, 0x7f, 0x70, 0xef, 0xfd, 0xc9, 0xad, 0xff, 0x9b, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0xe0, 0x1b, 0xcd, 0x73, 0x03, 0x00, 0x00,
}

func (m *Base64) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Base64) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Base64) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Base64Spec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Base64Spec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Base64Spec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.FieldPath)
	copy(dAtA[i:], m.FieldPath)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.FieldPath)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Base64Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Base64Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Base64Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Output)
	copy(dAtA[i:], m.Output)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Output)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Base64) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *Base64Spec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FieldPath)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *Base64Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Output)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Base64) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Base64{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "Base64Spec", "Base64Spec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "Base64Status", "Base64Status", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Base64Spec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Base64Spec{`,
		`FieldPath:` + fmt.Sprintf("%v", this.FieldPath) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Base64Status) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Base64Status{`,
		`Output:` + fmt.Sprintf("%v", this.Output) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Base64) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Base64: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Base64: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Base64Spec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Base64Spec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Base64Spec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FieldPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Base64Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Base64Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Base64Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Output = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
