apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo-crd-converter
  name: foo-crd-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-crd-converter
  template:
    metadata:
      labels:
        app: foo-crd-converter
    spec:
      containers:
      - image: ko://github.com/phosae/x-kubernetes/api/crdconversion
        env:
        - name: TLS_CERT
          value: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFDZ0F3SUJBZ0lRQm12UVRkb1JyblBPUWtlWUlpQTBlVEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3BMZFdKbGNtNWxkR1Z6TUNBWERUY3dNREV3TVRBd01EQXdNRm9ZRHpJd09EUXdNVEk1TVRZdwpNREF3V2pBVk1STXdFUVlEVlFRS0V3cExkV0psY201bGRHVnpNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFeHNlUXZuTVFwa1l5clRHU1ZtQSsvYURRYm9TQ2pPaXlGZFhhR2hzM05jWTBnQ0ZJQ2hiZVhRdlkKNENhYTk2OFJTMW5zejJEZGxlRjhmUHJhYXI2UlBLT0J6ekNCekRBT0JnTlZIUThCQWY4RUJBTUNBb1F3RXdZRApWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVSVXhECjJqZkt2cU1WelZ1MFl1NGNHSDR0UWQ4d2RRWURWUjBSQkc0d2JJSU5LaTVrWldaaGRXeDBMbk4yWTRJTEtpNW8KWld4c2J5NXpkbU9DR3lvdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJWktpNW9aV3hzYnk1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJY0Vmd0FBQVljUUFBQUFBQUFBQUFBQUFBQUFBQUFBQVRBS0JnZ3Foa2pPClBRUURBZ05KQURCR0FpRUEwWGgxWkpEKzBRY2JBaFZMQ3FydHZ2dlZLYXJpRlJ0TXdLVWJyQWZoNnFvQ0lRQ1gKczN3WWszdWcrQ2hGejZHc3RyMjM0emVyOXpsd1Y3UUtGeFNOdmdXVTdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
        - name: TLS_KEY
          value: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2RQeS90T1ZWR1pqNU5RSlQKb3g1QUdTNzJma1UyZUtRY1k2MG5haWVGVDVhaFJBTkNBQVRHeDVDK2N4Q21Sakt0TVpKV1lENzlvTkJ1aElLTQo2TElWMWRvYUd6YzF4alNBSVVnS0Z0NWRDOWpnSnByM3J4RkxXZXpQWU4yVjRYeDgrdHBxdnBFOAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=='
        name: converter
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo-crd-converter
  name: foo-crd-converter
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: foo-crd-converter
  type: ClusterIP