//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
boilerplate text in generated file header
*/

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/phosae/x-kubernetes/api/hello.zeng.dev/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&v1.Foo{}, func(obj interface{}) { SetObjectDefaults_Foo(obj.(*v1.Foo)) })
	scheme.AddTypeDefaultingFunc(&v1.FooList{}, func(obj interface{}) { SetObjectDefaults_FooList(obj.(*v1.FooList)) })
	return nil
}

func SetObjectDefaults_Foo(in *v1.Foo) {
	SetDefaults_Foo(in)
}

func SetObjectDefaults_FooList(in *v1.FooList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Foo(a)
	}
}
