apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.hello.zeng.dev
spec:
  group: hello.zeng.dev
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
    shortNames: ["fo"]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: false
      additionalPrinterColumns:
        - name: age
          jsonPath: .metadata.creationTimestamp
          type: date
        - name: message
          jsonPath: .spec.msg
          type: string
        - name: message1
          jsonPath: .spec.msg1
          type: string
          priority: 1 # kubectl get fo -o wide
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - msg
              properties:
                msg:
                  description: Msg says hello world!
                  type: string
                msg1:
                  description: Msg1 provides some verbose information
                  type: string
    - name: v2
      served: true
      storage: true
      additionalPrinterColumns:
        - name: status
          jsonPath: .status.phase
          type: string
        - name: age
          jsonPath: .metadata.creationTimestamp
          type: date
        - name: message
          jsonPath: .spec.config.msg
          type: string
          priority: 1
        - name: message1
          jsonPath: .spec.config.msg1
          type: string
          priority: 1
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - config
                - image
              properties:
                config:
                  description: Config is the configuration used by foo container
                  type: object
                  required:
                    - msg
                  properties:
                    msg:
                      description: Msg says hello world!
                      type: string
                    msg1:
                      description: Msg1 provides some verbose information
                      type: string
                image:
                  description: Container image that the container is running to do our foo work
                  type: string
            status:
              type: object
              properties:
                conditions:
                  description: Represents the latest available observations of a foo's current state
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                phase:
                  description: The phase of a Foo is a simple, high-level summary of where the Foo is in its lifecycle
                  type: string
