//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
boilerplate text in generated file header
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v2

import (
	unsafe "unsafe"

	hellozengdev "zeng.dev/crdconversion/internal/api/hello.zeng.dev"
	v2 "github.com/phosae/x-kubernetes/api/hello.zeng.dev/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v2.Foo)(nil), (*hellozengdev.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_Foo_To_hellozengdev_Foo(a.(*v2.Foo), b.(*hellozengdev.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.Foo)(nil), (*v2.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_Foo_To_v2_Foo(a.(*hellozengdev.Foo), b.(*v2.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v2.FooCondition)(nil), (*hellozengdev.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooCondition_To_hellozengdev_FooCondition(a.(*v2.FooCondition), b.(*hellozengdev.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.FooCondition)(nil), (*v2.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_FooCondition_To_v2_FooCondition(a.(*hellozengdev.FooCondition), b.(*v2.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v2.FooConfig)(nil), (*hellozengdev.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooConfig_To_hellozengdev_FooConfig(a.(*v2.FooConfig), b.(*hellozengdev.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.FooConfig)(nil), (*v2.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_FooConfig_To_v2_FooConfig(a.(*hellozengdev.FooConfig), b.(*v2.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v2.FooList)(nil), (*hellozengdev.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooList_To_hellozengdev_FooList(a.(*v2.FooList), b.(*hellozengdev.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.FooList)(nil), (*v2.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_FooList_To_v2_FooList(a.(*hellozengdev.FooList), b.(*v2.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v2.FooSpec)(nil), (*hellozengdev.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooSpec_To_hellozengdev_FooSpec(a.(*v2.FooSpec), b.(*hellozengdev.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.FooSpec)(nil), (*v2.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_FooSpec_To_v2_FooSpec(a.(*hellozengdev.FooSpec), b.(*v2.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v2.FooStatus)(nil), (*hellozengdev.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v2_FooStatus_To_hellozengdev_FooStatus(a.(*v2.FooStatus), b.(*hellozengdev.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hellozengdev.FooStatus)(nil), (*v2.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hellozengdev_FooStatus_To_v2_FooStatus(a.(*hellozengdev.FooStatus), b.(*v2.FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v2_Foo_To_hellozengdev_Foo(in *v2.Foo, out *hellozengdev.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_FooSpec_To_hellozengdev_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v2_FooStatus_To_hellozengdev_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_Foo_To_hellozengdev_Foo is an autogenerated conversion function.
func Convert_v2_Foo_To_hellozengdev_Foo(in *v2.Foo, out *hellozengdev.Foo, s conversion.Scope) error {
	return autoConvert_v2_Foo_To_hellozengdev_Foo(in, out, s)
}

func autoConvert_hellozengdev_Foo_To_v2_Foo(in *hellozengdev.Foo, out *v2.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_hellozengdev_FooSpec_To_v2_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_hellozengdev_FooStatus_To_v2_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_hellozengdev_Foo_To_v2_Foo is an autogenerated conversion function.
func Convert_hellozengdev_Foo_To_v2_Foo(in *hellozengdev.Foo, out *v2.Foo, s conversion.Scope) error {
	return autoConvert_hellozengdev_Foo_To_v2_Foo(in, out, s)
}

func autoConvert_v2_FooCondition_To_hellozengdev_FooCondition(in *v2.FooCondition, out *hellozengdev.FooCondition, s conversion.Scope) error {
	out.Type = hellozengdev.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_v2_FooCondition_To_hellozengdev_FooCondition is an autogenerated conversion function.
func Convert_v2_FooCondition_To_hellozengdev_FooCondition(in *v2.FooCondition, out *hellozengdev.FooCondition, s conversion.Scope) error {
	return autoConvert_v2_FooCondition_To_hellozengdev_FooCondition(in, out, s)
}

func autoConvert_hellozengdev_FooCondition_To_v2_FooCondition(in *hellozengdev.FooCondition, out *v2.FooCondition, s conversion.Scope) error {
	out.Type = v2.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_hellozengdev_FooCondition_To_v2_FooCondition is an autogenerated conversion function.
func Convert_hellozengdev_FooCondition_To_v2_FooCondition(in *hellozengdev.FooCondition, out *v2.FooCondition, s conversion.Scope) error {
	return autoConvert_hellozengdev_FooCondition_To_v2_FooCondition(in, out, s)
}

func autoConvert_v2_FooConfig_To_hellozengdev_FooConfig(in *v2.FooConfig, out *hellozengdev.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_v2_FooConfig_To_hellozengdev_FooConfig is an autogenerated conversion function.
func Convert_v2_FooConfig_To_hellozengdev_FooConfig(in *v2.FooConfig, out *hellozengdev.FooConfig, s conversion.Scope) error {
	return autoConvert_v2_FooConfig_To_hellozengdev_FooConfig(in, out, s)
}

func autoConvert_hellozengdev_FooConfig_To_v2_FooConfig(in *hellozengdev.FooConfig, out *v2.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_hellozengdev_FooConfig_To_v2_FooConfig is an autogenerated conversion function.
func Convert_hellozengdev_FooConfig_To_v2_FooConfig(in *hellozengdev.FooConfig, out *v2.FooConfig, s conversion.Scope) error {
	return autoConvert_hellozengdev_FooConfig_To_v2_FooConfig(in, out, s)
}

func autoConvert_v2_FooList_To_hellozengdev_FooList(in *v2.FooList, out *hellozengdev.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]hellozengdev.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_FooList_To_hellozengdev_FooList is an autogenerated conversion function.
func Convert_v2_FooList_To_hellozengdev_FooList(in *v2.FooList, out *hellozengdev.FooList, s conversion.Scope) error {
	return autoConvert_v2_FooList_To_hellozengdev_FooList(in, out, s)
}

func autoConvert_hellozengdev_FooList_To_v2_FooList(in *hellozengdev.FooList, out *v2.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v2.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_hellozengdev_FooList_To_v2_FooList is an autogenerated conversion function.
func Convert_hellozengdev_FooList_To_v2_FooList(in *hellozengdev.FooList, out *v2.FooList, s conversion.Scope) error {
	return autoConvert_hellozengdev_FooList_To_v2_FooList(in, out, s)
}

func autoConvert_v2_FooSpec_To_hellozengdev_FooSpec(in *v2.FooSpec, out *hellozengdev.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v2_FooConfig_To_hellozengdev_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_FooSpec_To_hellozengdev_FooSpec is an autogenerated conversion function.
func Convert_v2_FooSpec_To_hellozengdev_FooSpec(in *v2.FooSpec, out *hellozengdev.FooSpec, s conversion.Scope) error {
	return autoConvert_v2_FooSpec_To_hellozengdev_FooSpec(in, out, s)
}

func autoConvert_hellozengdev_FooSpec_To_v2_FooSpec(in *hellozengdev.FooSpec, out *v2.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_hellozengdev_FooConfig_To_v2_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_hellozengdev_FooSpec_To_v2_FooSpec is an autogenerated conversion function.
func Convert_hellozengdev_FooSpec_To_v2_FooSpec(in *hellozengdev.FooSpec, out *v2.FooSpec, s conversion.Scope) error {
	return autoConvert_hellozengdev_FooSpec_To_v2_FooSpec(in, out, s)
}

func autoConvert_v2_FooStatus_To_hellozengdev_FooStatus(in *v2.FooStatus, out *hellozengdev.FooStatus, s conversion.Scope) error {
	out.Phase = hellozengdev.FooPhase(in.Phase)
	out.Conditions = *(*[]hellozengdev.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v2_FooStatus_To_hellozengdev_FooStatus is an autogenerated conversion function.
func Convert_v2_FooStatus_To_hellozengdev_FooStatus(in *v2.FooStatus, out *hellozengdev.FooStatus, s conversion.Scope) error {
	return autoConvert_v2_FooStatus_To_hellozengdev_FooStatus(in, out, s)
}

func autoConvert_hellozengdev_FooStatus_To_v2_FooStatus(in *hellozengdev.FooStatus, out *v2.FooStatus, s conversion.Scope) error {
	out.Phase = v2.FooPhase(in.Phase)
	out.Conditions = *(*[]v2.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_hellozengdev_FooStatus_To_v2_FooStatus is an autogenerated conversion function.
func Convert_hellozengdev_FooStatus_To_v2_FooStatus(in *hellozengdev.FooStatus, out *v2.FooStatus, s conversion.Scope) error {
	return autoConvert_hellozengdev_FooStatus_To_v2_FooStatus(in, out, s)
}
